# Generated by Django 5.0.7 on 2024-08-14 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_product_star_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 8, 14, 9, 51, 9, 151745)
            ),
        ),
    ]
